// Generated by Claude/ChatGPT - reviewed by [Nolo Cárdeno] - [13/04/2026]

// Import required module
const express = require('express');

// Create a router instance
const router = express.Router();

/**
 * GET /tasks
 * Returns a list of mock tasks
 */
router.get('/tasks', async (req, res) => {
  try {
    // Extract 'limit' from query parameters
    const { limit } = req.query;

    // Input validation: if limit exists, it must be a positive number
    if (limit !== undefined) {
      const parsedLimit = Number(limit);

      // Check if it's a valid number and greater than 0
      if (isNaN(parsedLimit) || parsedLimit <= 0) {
        return res.status(400).json({
          success: false,
          data: null,
          error: 'Invalid "limit" parameter. Must be a positive number.'
        });
      }
    }

    // Mock data (in real app, this would come from a database)
    const tasks = [
      { id: 1, title: 'Learn Express', completed: false },
      { id: 2, title: 'Build API', completed: true },
      { id: 3, title: 'Write tests', completed: false }
    ];

    // Apply limit if provided
    const limitedTasks = limit ? tasks.slice(0, Number(limit)) : tasks;

    // Return successful response
    return res.status(200).json({
      success: true,
      data: limitedTasks,
      error: null
    });

  } catch (error) {
    // Catch unexpected errors
    console.error('Error in GET /tasks:', error);

    return res.status(500).json({
      success: false,
      data: null,
      error: 'Internal server error'
    });
  }
});

// Export router to use in main app
module.exports = router;